name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        run: |
          yarn build --base ${{ github.event.repository.name }}
          mv dist docs
      - name: Add build to GH pages branch
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@github.com'
          git checkout -B gh-pages
          git add -f docs
          git commit -m "Add artifacts"
          git push origin gh-pages -f
          git commit -m "Build pages" --allow-empty
          git push origin gh-pages
